### PR TITLE
feat: bump release level to production/stable

### LINKED ISSUE #59: Release as GA
[GA release template](https://github.com/googleapis/google-cloud-common/issues/287)
## Required 

- [ ] 28 days elapsed since last beta release with new API surface 
- [x] Server API is GA
- [x] Package API is stable, and we can commit to backward compatibility
- [x] All dependencies are GA

### PR DESCRIPTION
**Pull request by parthea**
Fixes #59 🦕

Release-As: 1.0.0

### CODE REVIEW

**Comment by parthea** [comment]
Wait for August 24 2021

**Comment by parthea** [comment]
Wait until 28 days after the release where #63 is solved

**Comment by tseaver** [comment]
@parthea 
> Wait until 28 days after the release where #63 is solved

I presume this is after #64 merges.  Is 28 days the standard interval for `beta` -> `ga`?  Or is that because #64 contains quasi-breaking changes (moving imports)?

**Comment by parthea** [comment]
> I presume this is after #64 merges. 

Correct. The 28 day timer will start when we publish the release after #64 is merged.

> Is 28 days the standard interval for beta -> ga? 

Correct. It is standard interval for beta->ga where we wait 28 days after releasing a client which includes a stable endpoint.

> Or is that because #64 contains quasi-breaking changes (moving imports)?

Correct, and I also think it's a good idea to reset the 28 day timer since I don't think we've released a version of this library which included a working v1 client. The [last release had a broken v1 client](#63).

**Review by busunkim96 — APPROVED** [review]

**Pull request merged**
